# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiles', '0002_auto_20151225_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tile',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
